#!/bin/bash
# How to run: Just run it. Just `devbox` you don't need to set options.

set -euo pipefail

PORT_NB=${PORT_NB:-$([ "$SLURM_CLUSTER_NAME" = "fair-sc" ] && echo 8889 || echo 8888)}
PORT_FB=${PORT_FB:-$([ "$SLURM_CLUSTER_NAME" = "fair-sc" ] && echo 1338 || echo 1337)}
PORT_SM=${PORT_SM:-$([ "$SLURM_CLUSTER_NAME" = "fair-sc" ] && echo 2338 || echo 2337)}

SESS="devbox"

if tmux has-session -t $SESS 2>/dev/null; then
  echo -n "tmux session '$SESS' already exists. Attach (a), Kill (k), or do nothing (n)? "
  read -r choice
  case "$choice" in
    a)
      tmux attach-session -t $SESS
      exit 0
      ;;
    k)
      tmux kill-session -t $SESS
      echo "Killed. Note, this does not scancel any potentially running devgpu."
      sleep 1  # Give it a sec, and then continue the script below.
      ;;
    *)
      exit 0
      ;;
  esac
fi

tmux new-session -d -s "$SESS"

# Three-way split:
tmux split-window -v -t "$SESS:0" \; \
     select-layout -t "$SESS:0" even-vertical
tmux split-window -h -t "$SESS:0.0"

ENTER=${ENTER:-C-m}
tmux send-keys -t "$SESS:0.0" "smanager --port $PORT_SM" $ENTER
tmux send-keys -t "$SESS:0.1" "fbi-serve --port $PORT_FB --prefs-dir /checkpoint/rigi/$USER --share-dir /checkpoint/rigi/shares --maxdepth 2 --dataset /checkpoint/rigi/bv2/workdirs" $ENTER
tmux send-keys -t "$SESS:0.2" "env PORT_NB=$PORT_NB ~/rigi/devbox_launch_inner" $ENTER

echo -e "To forward to your laptop, run:"
echo -e "\033[34mssh -N -f -L localhost:$PORT_NB:localhost:$PORT_NB -L localhost:$PORT_FB:localhost:$PORT_FB -L localhost:$PORT_SM:localhost:$PORT_SM $SLURM_CLUSTER_NAME\033[0m"
echo "Tmux session '$SESS' created, to attach, just re-launch this script or tmux a -t $SESS"
tmux a -t $SESS
