#!/bin/bash

#SBATCH --account rigi
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --time=7-0:0:0
#SBATCH --output=/checkpoint/rigi/bv2/slurm_out/%u/%j.txt
set -x

MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
MASTER_PORT=$((10000 + SLURM_JOB_ID % 50000))

echo $CONDA_PREFIX
pwd

torchrun --nnodes="$SLURM_NNODES" --nproc_per_node=gpu --rdzv_backend=c10d --rdzv_endpoint="${MASTER_ADDR}:${MASTER_PORT}" --rdzv_id="$SLURM_JOB_ID" "$@"
