#!/bin/bash

MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
MASTER_PORT=$((10000 + SLURM_JOB_ID % 50000))

(set -x; cd rsc && ~/rsc/cenv/bin/torchrun --nnodes="$SLURM_NNODES" --nproc_per_node=gpu --rdzv_backend=c10d --rdzv_endpoint="${MASTER_ADDR}:${MASTER_PORT}" --rdzv_id="$SLURM_JOB_ID" "$@")
