#!/bin/bash
# NOTE: this needs to run from
#SBATCH --job-name=bv2-nightly
#SBATCH --account rigi
#SBATCH --qos h200_dev
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --gpus-per-node=2
#SBATCH --time=00:15:00
#SBATCH --output=/checkpoint/rigi/bv2/nightlies/z_run_%j.txt

DATE=$(date +%y-%m-%d-%a_%H%M%S)

# SBATCH doesn't have something with date for filename, so we redirect.
exec > /checkpoint/rigi/bv2/nightlies/run_${DATE}.txt 2>&1

echo "Start nightly at ${DATE}"
cd ~/rigi-nightly

echo "Updating git..."
GIT_SSH_COMMAND='ssh -i ~/.ssh/github_readonly' git fetch origin
git reset --hard origin/main

echo "Running GPU-based unit tests..."
python -m pytest -s bv2 -m gpu --json-report --json-report-file=report.json

echo "Running job..."
~/rigi/bv2/tools/launch_fair_srun -m bv2.train name:=nightly_random_nouns_${DATE}

# Re-submit the job
echo "Rescheduling for in a day: $0"
sbatch --begin=now+1day "$0"

sleep 10
echo "Bye!"
