#!/bin/bash
# NOTE: this needs to run from
#SBATCH --job-name=bv2-nightly
#SBATCH --account rigi
#SBATCH --qos h200_dev
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --gpus-per-node=2
#SBATCH --time=00:10:00
#SBATCH --output=/checkpoint/rigi/bv2/nightlies/run_%j.txt

echo "Start nightly at $(date)"
cd ~/rigi-nightly

echo "Updating git..."
GIT_SSH_COMMAND='ssh -i ~/.ssh/github_readonly' git fetch origin
git reset --hard origin/main

echo "Running job..."
~/rigi/bv2/tools/launch_fair_srun -m bv2.train name:=nightly_random_nouns_`date +'%y-%m-%d-%a'`

# Re-submit the job
echo "Rescheduling for in a day: $0"
sbatch --begin=now+1day "$0"

sleep 10
echo "Bye!"
