#!/bin/bash

# NOTE both do not end with a slash.
SRC="${1:-$HOME/rigi}"
DST="${2:-fair-sc-3:~/rigi}"

# ENSURE that both do not end with a slash.
SRC="${SRC%/}"
DST="${DST%/}"
# However, below we'll always USE SRC with a slash and DST without.

# Put common excludes in an array (easy to extend)
EXCLUDES=(
  --exclude='.git/'
  --exclude='__pycache__/'
  --exclude='/venv*/'
)

sync_once() {
  rsync -az --delete "${EXCLUDES[@]}" "$SRC/" "$DST"
  echo "Files synchronized at $(date)"
}

sync_once
# Watch for modify/create/delete events recursively and rsync again on any event
while inotifywait -r -e modify,create,delete,move "$SRC/"; do
  sync_once
done
